### ISSUE TITLE
to-do list: additional features

### ISSUE THREAD

**Issue by eseutella** [eseutella/safe_space#10]
- [ ] edit existing list name
- [ ] edit existing task name
- [x] sort lists by name 
- [x] sort tasks by completed, followed by name
- [ ] search list function
